---
- name: Servers
  hosts: prod
  tasks:
- name: Motd
  hosts: prod
  tasks:
    - name: Upload local-storage-file-dymotd.sh
      become: yes
      copy:
        src: /home/parallels/git/sdvps-homeworks/ansible/7.2/files/html.sh
        dest: /tmp    
    - name: Chmod file dymotd.sh
      become: yes
      ansible.builtin.file:
        path: /tmp/html.sh
        mode: a+x
  #  - name: Add line profile
  #    become: yes
  #    ansible.builtin.lineinfile:
  #      path: /etc/profile
  #      line: /usr/local/sbin/dymotd.sh


