---
- name: Servers
  hosts: prod
  tasks:
- name: Motd
  hosts: prod
  tasks:
    - name: Upload local-storage-file-dymotd.sh
      become: yes
      copy:
        src: /home/parallels/git/sdvps-homeworks/ansible/7.2/files/dymotd.sh
        dest: /tmp    
    - name: Chmod file dymotd.sh
      become: yes
      ansible.builtin.file:
        path: /tmp/dymotd.sh
        mode: a+x
    - name: Add line profile
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/profile
        line: /usr/local/sbin/dymotd.sh
    - name: Upload local-storage-file-bash.sh
      become: yes
      copy:
        src: /home/parallels/git/sdvps-homeworks/ansible/7.2/files/html.sh
        dest: /tmp    
    - name: Chmod file html.sh
      become: yes
      ansible.builtin.file:
        path: /tmp/html.sh
        mode: a+x
    - name: Execute the script
      become: yes
      script: sh /tmp/html.sh
        remote_src: yes
  #  - name: Add line profile
  #    become: yes
  #    ansible.builtin.lineinfile:
  #     path: /etc/profile
  #      line: /usr/local/sbin/dymotd.sh

