---
- name: Install Apache
  become: true
  yum:
    name: httpd
    state: present
- name: Upload local-storage-file-bash.sh
  become: yes
  copy:
    src: /home/parallels/git/sdvps-homeworks/ansible/7.2/files/html.sh
    dest: /tmp    
- name: Chmod file html.sh
  become: yes
  ansible.builtin.file:
    path: /tmp/html.sh
    mode: a+x
- name: script
  become: yes
  command: sh /tmp/html.sh
- name: Copy index.html
  become: yes
  ansible.builtin.copy:
    src: /tmp/index.html
    dest: /var/www/html/
    remote_src: yes
