---
# tasks file for apache
  - name: Install Apache
    become: yes
    yum:
      name: httpd
      state: latest
  - name: Show fact
    debug:
      msg: "{{ ansible_processor }}"
  - debug:
      msg: "{{ ansible_default_ipv4.address }}"
  - debug:
      msg: "{{ ansible_userspace_architecture }}"
  - debug:
      msg: "{{ ansible_devices.vda.partitions.vda2.size}}"
  - debug:
      msg: "{{ ansible_hostname }}"
  - set_fact: full_message= "{{ ansible_processor }} {{ ansible_default_ipv4.address }} {{ ansible_userspace_architecture }}{{ ansible_devices.vda.partitions.vda2}} {{ ansible_hostname }}"
  - name: Copy ansible facts to a file.
    copy:
      content: "{{ ansible_processor }} {{ ansible_default_ipv4.address }} {{ ansible_userspace_architecture }}{{ ansible_devices.vda.partitions.vda2}} {{ ansible_hostname }}"
      dest: /tmp/index.html
        
  - name: Copy index.html
    become: yes
    ansible.builtin.copy:
      src: /tmp/index.html
      dest: /var/www/html/
      remote_src: yes

  - name: Start service httpd
    become: yes
    ansible.builtin.service:
      name: httpd
      state: started

  - name: Pause play until a URL is reachable from this host
    uri:
      url: "http://127.0.0.1"
      follow_redirects: none
      method: GET
    register: _result
    until: _result.status == 200

