---
- name: Servers
  hosts: prod
  tasks:
    - name: Download APACHE KAFKA
      get_url:
        url: https://dlcdn.apache.org/kafka/3.0.0/kafka-3.0.0-src.tgz
        dest: /tmp/kafka-3.0.0-src.tgz
     #  mode: '0440'
     #register: download_kafka
     #until: download_kafka is succeeded  
    - name: Unarchive zip Kafka
      ansible.builtin.unarchive:
        src: /tmp/kafka-3.0.0-src.tgz
        dest: /tmp
        remote_src: yes
- name: Tuned
  hosts: prod
  tasks:
    - name: INSTALL Tuned
      yum:
        name:
          - mc
          - tuned
        state: present
    - name: Start service tuned
      ansible.builtin.service:
        name: tuned
        state: started
        enabled: yes
- name: Motd
  hosts: prod
  tasks:
    - name: Change Motd
      copy:
      dest: "/etc/update-motd.d/99-netology"
      content: |
        Hello, netology
        wellcome server
    - name: Chmod
      - name: Chmod 99-netology
        ansible.builtin.file:
        path: /etc/update-motd.d/99-netology
        mode: '755'
