---
- name: Servers
  hosts: prod
  tasks:
    - name: Download APACHE KAFKA
      get_url:
        url: https://dlcdn.apache.org/kafka/3.0.0/kafka-3.0.0-src.tgz
        dest: /tmp/kafka-3.0.0-src.tgz
     #  mode: '0440'
     #register: download_kafka
     #until: download_kafka is succeeded  
    - name: Unarchive zip Kafka
      ansible.builtin.unarchive:
        src: /tmp/kafka-3.0.0-src.tgz
        dest: /tmp
        remote_src: yes
        