---
- name: Servers
  hosts: prod
  tasks:
    - name: Download APACHE KAFKA
        get_url:
        url: https://www.apache.org/dyn/closer.cgi?path=/kafka/3.0.0/kafka-3.0.0-src.tgz
        dest: /tmp/kafka-3.0.0-src.tgz
        mode: '0440'
        register: download_kafka
        until: download_kafka is succeeded
    - name: Use gzip to compress a single archive (i.e don't archive it first with tar)
      community.general.archive:
        path: /tmp/kafka-3.0.0-src.tgz
        dest: /tmp/kafka-3.0.0-src.tgz
        format: gz