version: '3.1'

services:
  master:
    image: mysql:8.0
    container_name: db-master-1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /docker_volume/v1_6_2/:/var/backup
    ports:
      - 3306
    networks:
      mysqlnet:
        ipv4_address: 10.5.0.2
  slave:
    image: mysql:8.0
    container_name: db-slave-1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /docker_volume/v1_6_2/:/var/backup
    networks:
      mysqlnet:
        ipv4_address: 10.5.0.3
networks:
  mysqlnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
